### ISSUE TITLE
Cannot pass the value

### ISSUE THREAD

**Issue by maxykato** [tokorom/SegueContext#1]
Hi, this library looks like an awesome tool, but I am struggling to get it work.
I write my codes as below, but the value in the destination controller is 0. (I assumed the value should be "10 " right?)

Would you advise me what might be a potential problem?

Source Controller:

```
    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath){
        if indexPath.section == 2 {
            performSegueWithIdentifier("playbackContent", sender: nil, context: 10)
        }
    }

    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
    if segue.identifier == "playbackContent"{
        let playbackContentVC : PlaybackContentViewController = (segue.destinationViewController as? PlaybackContentViewController)!
        }
    }
```

Destination Controller

```
    override func viewDidLoad() {
        super.viewDidLoad()

        if let value: Int = self.contextValue(){
            print(value)
        }   
    }
```

**Comment by tokorom** [comment]
@maxykato Thanks for your contact :)

Quick fix is add `super.prepareForSegue(segue, sender: sender)` in your `prepareForSegue`.

However, this is difficult to understand, I consider the improvement to continue.

**Comment by tokorom** [comment]
@maxykato I have improved this problem in ver 0.0.4 :+1:

**Comment by maxykato** [comment]
Wow! Yes, it worked. Thanks sooooo much. 
This will save a lot of time for me going forward :)

**Comment by tokorom** [comment]
:+1:
