### ISSUE TITLE
v1.1.0 should be v2.0 ?

### ISSUE THREAD

**Issue by hiragram** [tokorom/SegueContext#17]
Latest release v1.1.0 contains some breaking changes due to migration to Swift3.
If you follow the rule of semantic versioning, it should be major update.

I am working on a project using Swift2, and my Cartfile contains

```
github "tokorom/SegueContext" ~> 1.0.0
```

then I update dependencies, Swift3 version was fetched and failed to build framework.

**Comment by tokorom** [comment]
@hiragram Thanks for your comment :)

I will change the current version to 2.0.0.

**Comment by tokorom** [comment]
done :bow:

**Comment by hiragram** [comment]
Thanks!
