### ISSUE TITLE
fails validation with carthage 

### ISSUE THREAD

**Issue by ishidakei** [tokorom/SegueContext#22]
Using SegueContext with carthage, Xcode fails validation.

## Steps to Reproduce

1.  make a new project.

2. make a Cartfile: `github "tokorom/SegueContext"`

2. setup carthage to use SegueContext:
 `carthage update --platform iOS`
![image](https://cloud.githubusercontent.com/assets/1884122/26753493/80ec2a44-48a2-11e7-82db-7c6c8da1399c.png)
 ![image](https://cloud.githubusercontent.com/assets/1884122/26753494/95056dba-48a2-11e7-98a3-6d2f20a5e6ab.png)

3. In Xcode, Product > Archive

4. In Organizer, Validate the app.
![image](https://cloud.githubusercontent.com/assets/1884122/26753427/d7bd8f72-48a0-11e7-96e7-4cf530443747.png)
I don't know why libswiftRemoteMirror.dylib is contained in "Binary and Entitlements" 
 
5. Some minutes later, Organizer shows:
![image](https://cloud.githubusercontent.com/assets/1884122/26753454/b636da06-48a1-11e7-8284-6f00f52b0f96.png)

6. Organizer shows the same error to upload the app to Apple Store.

## Version
SegueContext 3.0.0
Xcode 8.3.2
carthage 0.23.0

**Comment by tokorom** [comment]
@ishidakei Thank you for your reporting :bow:

- The reported error is `Invalid bundle identifier`. Maybe either your xcode project's bundle identifier or iTunes connect's bundle identifier is wrong.

- On the other hand, SegueContext itself also had submission errors
    - #21 
    - I merged this fix in SegueContext version 3.0.1
    - Please retry with 3.0.1

**Comment by ishidakei** [comment]
Thank you for 3.0.1. It works quite well :thumbsup:
