### ISSUE TITLE
Errors on Xcode 7 GM seed

### ISSUE THREAD

**Issue by maxykato** [tokorom/SegueContext#5]
Today I updated my Xcode to Xcode 7 GM. 
When I built my project, I got lots of errors about SegueContext library.
I assume this is something the library needs to fix? 
If not, I would appreciate if you can advise me how to fix it.
![2015-09-10 14 10 28](https://cloud.githubusercontent.com/assets/6688608/9780654/742f3504-57c6-11e5-9443-92e2f12d7a7c.png)

**Comment by tokorom** [comment]
@maxykato 

I'm sorry confirmation is delayed :bow:
I have fixed these problems for Xcode 7.

Please check the version `0.2.0`.

**Comment by maxykato** [comment]
It works great! Thank you so much :)

**Comment by tokorom** [comment]
:smile_cat:
