### ISSUE TITLE
Carthage / Swift2.1 fails to build

### ISSUE THREAD

**Issue by hiragram** [tokorom/SegueContext#8]
I have updated Xcode from 7.0 to 7.1 and rebuild frameworks using Carthage, but Xcode fails to build app.

```
Module file was created by an older version of the compiler; rebuild 'SegueContext' and try again: /Users/name/Development/project/SegueContext.framework/Modules/SegueContext.swiftmodule/arm64.swiftmodule
```

Output of `xcode-select -p` is as follows: 

```
/Applications/Xcode7_1.app/Contents/Developer
```

Output of `xcodebuild -version` is as follows:

```
Xcode 7.1
Build version 7B91b
```

Do you know any solutions?

Isn't swift2.1 supported yet?

**Comment by tokorom** [comment]
@hiragram I'm sorry reply is delayed.

I think this is same with https://github.com/Carthage/Carthage/issues/633

Please try it -> https://github.com/Carthage/Carthage/issues/633#issuecomment-153700475

I was able to solve this problem.

**Comment by hiragram** [comment]
@tokorom Thx. I will try it.
